Pkg 2148 dask 2023.5.1
AnacondaRecipes/dask-feedstock pull request #31
Opened 2023-06-03 00:04 UTC by Jrice1317

2023-06-05 15:48 UTC, JeanChristopheMorinPerso requested changes

2023-06-05 15:48 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    # - click >=8.0
I'd remove them entirely.

2023-06-05 20:57 UTC, SC426 reviewed
LGTM once the comments from @JeanChristopheMorinPerso are addressed

2023-06-06 17:03 UTC, SC426 approved these changes

2023-06-06 17:05 UTC, merged